# Generated by Django 3.0.3 on 2020-08-05 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keratometry', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pachymetry', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cdva', models.DecimalField(decimal_places=2, max_digits=4)),
                ('udva', models.DecimalField(decimal_places=2, max_digits=4)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='url_pdf',
            new_name='pdf',
        ),
        migrations.AddField(
            model_name='paper',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Parameter')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Paper')),
            ],
        ),
    ]
