# Generated by Django 3.0.3 on 2020-08-05 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200805_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertext',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_texts', to='core.Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='core.Parameter'),
        ),
    ]
